# Generated by Django 5.0.6 on 2024-05-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_sheetmusic_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mp3',
        ),
    ]
