# Generated by Django 5.0.6 on 2024-06-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
