# Generated by Django 5.0.6 on 2024-06-22 06:48

import music.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_delete_customuser'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetmusic',
            name='file',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='lyrics',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='lyricsAuthor',
            field=models.TextField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='musicAuthor',
            field=models.TextField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='sheet_music', validators=[music.validators.validate_pdf_extension]),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='playable',
            field=models.FileField(blank=True, null=True, upload_to='mp3', validators=[music.validators.validate_audio_extension]),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='tjchymn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
