# Generated by Django 5.0.6 on 2024-07-13 05:32

import music.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_sheetmusic_file_sheetmusic_lyrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[music.validators.validate_pdf_extension]),
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='playable',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[music.validators.validate_audio_extension]),
        ),
    ]
